### ISSUE TITLE
Convert Static Dropdown to Dynamic Dropdown

### ISSUE THREAD

**Issue by Md-Kais** [Md-Kais/CUERS-New#20]
Currently, we have a static dropdown in our application that displays a fixed set of options to the user. However, we want to enhance the dropdown functionality by making it dynamic. 

A dynamic dropdown will allow us to populate the options dynamically based on certain conditions or data sources, providing a more flexible and user-friendly experience.

**Steps to Reproduce:**
1. Open the application and navigate to the page containing the static dropdown.
2. Observe the dropdown and note that it displays a fixed set of options.
3. There is no new button to select and write more options for this dropdown.

**Expected Behavior:**
The static dropdown should be transformed into a dynamic dropdown that can update its options based on specific conditions or data sources and also add new button to select and make more choices.

**Additional Details:**
To achieve a dynamic dropdown, the following changes are required:
1. Identify the conditions or data sources that will determine the options available in the dropdown.
2. Implement the necessary API calls(sql) to retrieve the dynamic options.
3. Update the dropdown component to handle the dynamic options and render them appropriately.
4. Add New button to create and select more options.

**Acceptance Criteria:**
- The static dropdown should be replaced with a dynamic dropdown that can fetch options from a data source.
- The options in the dropdown should update dynamically based on the specified conditions or data sources.
- The dropdown should maintain its functionality, allowing users to select an option as before.
- The dynamic dropdown implementation should be tested thoroughly to ensure its reliability and correctness.

**Note:**
It is recommended to discuss the implementation approach with the development team and consider any potential impact on other parts of the application. Additionally, ensure that appropriate error handling and fallback options are in place to handle scenarios where the dynamic options cannot be retrieved or updated.

**Comment by Md-Kais** [comment]
Another (possibly bug) and new feature:
- we also check dropdown.jsx cause its behavior is little bit unexpected. And we also have to add new button there @voidCounter .

**Comment by Md-Kais** [comment]
Hi there,

I have a proposal to address the issue we are facing with the `activity_type_id` in the database. Currently, the `activity_type_id` is stored as an English string, but we want to display it in Bengali language for dynamic dropdowns. To achieve this, I suggest the following solution:

1. Convert the `activity_type_id` to a string representation of Bengali numbers.
2. Store the `activity_type_id` as Bengali numbers in the database.
3. Use the Bengali number representation for displaying and processing the `activity_type_id` in the application.

By storing the `activity_type_id` as Bengali numbers and using them throughout the application, we can ensure consistency and compatibility with the desired Bengali language support for dynamic dropdowns.

Please let me know your thoughts on this proposal. I believe it will provide a suitable solution to address the issue and enable the functionality we need.

Thank you!

**Comment by Md-Kais** [comment]
@ImranIF @voidCounter Hi there,

I have a proposal to address the issue we are facing with the `activity_type_id` in the database. Currently, the `activity_type_id` is stored as an English string, but we want to display it in Bengali language for dynamic dropdowns. To achieve this, I suggest the following solution:

1. Convert the `activity_type_id` to a string representation of Bengali numbers.
2. Store the `activity_type_id` as Bengali numbers in the database.
3. Use the Bengali number representation for displaying and processing the `activity_type_id` in the application.

By storing the `activity_type_id` as Bengali numbers and using them throughout the application, we can ensure consistency and compatibility with the desired Bengali language support for dynamic dropdowns.

Please let me know your thoughts on this proposal. I believe it will provide a suitable solution to address the issue and enable the functionality we need.

Thank you!

**Comment by voidCounter** [comment]
@Md-Kais, currently we're not storing data of `number` type as Bengali in the database. Instead we've a module [toBanglaNumber.js](https://github.com/Md-Kais/CUERS-New/blob/main/src/Modules/toBanglaNumber.js) to convert incoming data(of `number` type) to Bengali representation. So we could use it before displaying on the UI.

**Comment by Md-Kais** [comment]
Then we can't make dynamic drop-down for activity type id
